// 

import type { Metadata, Viewport } from "next";
import "@/app/component/style/globals.css"
import TopBanner from "@/app/component/layout/Banner/page";
import TopNavbar from "@/app/component/layout/Navbar/Top/page";
import Footer from "@/app/component/layout/Footer/page";
import HolyLoader from "holy-loader";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "SHOP.CO",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#000000",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-serif">
        <HolyLoader color="#868686" />
        <TopBanner />
        <Providers>
          <TopNavbar />
          {children}
        </Providers>
        <Footer />
      </body>
    </html>
  );
}